config/routes.rb
Blog::Application.routes.draw do

  root :to => "posts#index"

  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
  validates_presence_of :name, :body

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments, :dependent => :destroy
  
  validates_presence_of :title, :body
  default_scope :order => 'created_at DESC'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    flash[:alert] = 'Falha ao salvar comentário!' unless @comment.save

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to @post }
      format.xml  { head :ok }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Postagem criada com sucesso!') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Postagem atualizada com sucesso!') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(resource)
    render "shared/error_messages_for", :resource => resource
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def cut_word(word, size)
    if word.length > size
      word = "#{word.slice(0..size)} ..."
    end
    word
  end
  
end

app/views/comments/_comment.html.erb
<div class="comment">
	<b><%= comment.name %></b> disse:<br/><%= link_to image_tag("delete.png"), post_comment_path(comment.post, comment), :method => :delete, :class => 'delete' %>
	<span>Postado: <%= time_ago_in_words comment.created_at %> atrás</span><br/><br/>
  <div class="body">
    <%= comment.body %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="form_comment">
<h3>Deixe seu comentário</h3>
<%= form_for [post, comment ] do |f| %>
	<%= error_messages_for comment %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog Unisul</title>
  <%= stylesheet_link_tag 'common' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

	<div id="header">
		<div id="logo"></div>
	</div>

	<div id="wrapper">
		
		<div id="content">
			<%= yield %>
		</div>
		
  	<div id="footer">
			&copy;Blog Unisul 2011
  	</div>

	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
	<%= error_messages_for @post %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= link_to '« Voltar', posts_path, :class => 'button' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= link_to 'Nova Postagem', new_post_path, :class => 'button' %>
<% @posts.each do |post| %>
	<div class="posts">
		<h2>
			<%= link_to post.title.titleize, post_path(post) %>
			<span>Postado <%= post.created_at %></span>
		</h2>
    <%= cut_word post.body, 605 %>
		<br/>
		<p>Comentários ( <%= post.comments.count %> )</p>
		<hr>
    <%= link_to 'Ver', post, :class => 'button' %>
    <%= link_to 'Editar', edit_post_path(post), :class => 'button' %>
    <%= link_to 'Excluir', post, :confirm => 'Are you sure?', :method => :delete, :class => 'button' %>
	</div>

<% end %>

app/views/posts/new.html.erb
<%= link_to '« Voltar', posts_path, :class => 'button' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= link_to '« Voltar', posts_path, :class => 'button' %>
<p id="notice"><%= notice %></p>

<h2>
	<%= link_to @post.title.titleize, post_path(@post) %>
	<span>Postado <%= @post.created_at %></span>
</h2>
<%= @post.body.html_safe %>

<div id="comments">
<% if @post.comments.any? %>
  <%= render @post.comments %>
<% else %>
  <p>Nenhum comentário ainda.</p>
<% end %>
</div>

<div id="comment_form">
  <%= render "comments/form", :post => @post, :comment => Comment.new %>
</div>

app/views/shared/_error_messages_for.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= t "error_message_header", :count => resource.errors.count, :model => resource.class.model_name.human %></h2>
    <ul><% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>